perf(Boards, MiscDrivers):  Reduce refresh time and add font color selection on TFT Display drivers for MAX32690
analogdevicesinc/msdk pull request #1107
Opened 2024-08-07 16:33 UTC by crsz20

### Description

Slight modifications to the TFT LCD display drivers on the MAX32690 EV Kit V1 board.
- Removed delays in `TFT_SPI_Write()` to reduce the screen refresh time from 0.87129 seconds to 0.120858 seconds -- an 86% improvement.
- `MXC_TFT_PrintFont()` would use the initially set background color around the printed text. Added a function to offer color selection of both the background and the font text.

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [x] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-08-08 16:27 UTC, crsz20 commented
/clang-format-run

2024-08-09 02:09 UTC, Jake-Carter requested changes

2024-08-09 02:09 UTC, Jake-Carter commented on Libraries/MiscDrivers/Display/tft_st7735.h
> + * @param       id              Font number ID
Should be `@param font_id`, or rename the variable in the function declaration to `id`.

2024-08-12 14:51 UTC, EricB-ADI commented on Libraries/Boards/MAX32690/EvKit_V1/Source/board.c
> -            for (int k = 0; k < 2; k++) {}
I would be shocked if that for loop was not being optimized away.

2024-08-12 15:03 UTC, EricB-ADI commented
Closing this as we no longer have access to the fork. Same changes in #1110

2024-08-12 15:03 UTC, closed without merging