feat(PeriphDrivers): API to get the package type of part and test date.
analogdevicesinc/msdk pull request #1243
Opened 2024-10-25 14:41 UTC by EricB-ADI

## Pull Request Template

### Description

Starting in 10/23, the USN was updated to include the test date and package type. These APIs cover getting those.

2024-10-25 15:22 UTC, EricB-ADI commented
/clang-format-run

2024-10-25 16:02 UTC, EricB-ADI commented
/clang-format-run

2024-10-25 16:22 UTC, sihyung-maxim approved these changes

2024-10-25 16:38 UTC, sihyung-maxim requested changes
build not working, unapproving

2024-10-28 19:20 UTC, EricB-ADI commented
/clang-format-run

2024-10-28 19:28 UTC, EricB-ADI commented
/clang-format-run

2024-12-13 17:28 UTC, EricB-ADI commented
not stale just busy

2025-02-19 18:04 UTC, closed without merging