chore(Documentation): Update documentation to use the ADI Harmonic theme
analogdevicesinc/msdk pull request #1257
Opened 2024-11-06 20:55 UTC by glen-anderson

### Description

Closes #1149 and moves the needle a bit on #1148 

Update the documentation to better follow ADI guidelines:

- Update the doc theme to use the [harmonic-mkdocs-theme](https://github.com/analogdevicesinc/harmonic-mkdocs-theme) theme
- Break the monolithic `USERGUIDE.md` into smaller top-level markdown files
- Remove the generated doxygen files from the repo since they're generated at build time
- Remove doxygen build steps from `.github/workflows/build-docs.yml` since they're taken care of in `Documentation/build.py`
- Refactor `Documentation/build.py` to be a bit easier to maintain
- Add  [markdownlint](https://github.com/DavidAnson/markdownlint) config to catch inconsistencies. I recommend the [VS Code plugin](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint)
- Fix and normalized all the markdown to follow lint rules

Happy to take feedback on this and update/modify as necessary.

### Testing

Best to start from a clean workspace but it should work regardless.

```sh
git clean -dfx
python -m venv venv
source venv/bin/activate # or venv\Scripts\activate on Windows
pip install -r Documentation/requirements.txt
python Documentation/build.py
mkdocs serve
```

![image](https://github.com/user-attachments/assets/fccc4030-0b21-4a53-9da8-d9f0882b517e)

![image](https://github.com/user-attachments/assets/8ab5db0e-1ab5-464b-b7b0-2a19ce3ef728)

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [x] Description of changes and all other relevant information.
- [x] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-11-13 16:57 UTC, sihyung-maxim requested changes
Looks good - definitely nice to see the user guide partitioned out which makes it easier to navigate.

Double-check me on the "???+ ..." formatting though.

2024-11-13 16:57 UTC, sihyung-maxim commented on Documentation/MAX32520.html
Your thoughts on removing these files, @lorne-maxim?

It helps with navigation and provides some other information if users prefer going through this route, but the files are outdated. If we keep these, then they need to be updated as well - though I'm not sure what resources are available for this.

2024-11-13 16:57 UTC, sihyung-maxim commented on Documentation/user-guide/getting-started.md
> +The MSDK is designed for both evaluation and end-application development. The typical **evaluation** cycle usually involves setting up the development environment, running demos, and exercising the p
`typical **development** cycle typically` sounds redundant.

2024-11-13 16:57 UTC, sihyung-maxim commented on Documentation/user-guide/index.md
> +* Windows (Windows 10 only)
MSDK works on Windows 11 as well now.

2024-11-13 16:57 UTC, sihyung-maxim commented on mkdocs.yml
> +copyright: 'Copyright (C) 2022-2023 Maxim Integrated Products, Inc. All Rights Reserved. (now owned by Analog Devices, Inc.), Copyright (C) 2023-2024 Analog Devices, Inc. All Rights Reserved. This so
The `This software is proprietary to Analog Devices, Inc. and its licensors.` line can be deleted. This line should have also been removed from most other files within the MSDK due to the permissive licensing of the MSDK.

2024-12-17 20:15 UTC, glen-anderson commented on Documentation/user-guide/board-support-pkgs.md
> +    The first task when opening or creating any project is to ensure the BSP is set correctly.
Thanks @sihyung-maxim, this syntax is specific to the theme we're using and renders like this:

![image](https://github.com/user-attachments/assets/d95abdda-d924-4440-a929-502e8a8d5ead)

2024-12-17 20:16 UTC, glen-anderson commented on Documentation/MAX32520.html
Ping @lorne-maxim

2025-01-24 00:13 UTC, closed without merging