fix(Other): fix if defined() in wrapper files
analogdevicesinc/msdk pull request #1278
Opened 2024-11-21 19:39 UTC by mattsm

The 'if defined(FOO) || BAR' lines are not clear

$ sed 's, (CONFIG_SOC, defined(CONFIG_SOC,g' -i $(git grep --name-only  if.defined\(.*\|\|.\() $ sed 's,||\s*\\$,\|\| \\,g' -i $(git grep --name-only '||.*\\$')

### Description

Not much to add other than the subject of the single git commit above.

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-12-03 18:19 UTC, sihyung-maxim approved these changes
@ozersa

2024-12-03 18:27 UTC, sihyung-maxim commented
The [pull request template](https://github.com/analogdevicesinc/msdk/blob/main/.github/pull_request_template.md) contains guidelines on how to title PRs. The guidelines also appear in the description when opening a PR.

2024-12-04 11:36 UTC, ozersa requested changes
It is not a fix, just a coding style change.

Could you change PR title as "style(Other): ...."

2024-12-04 15:45 UTC, MaureenHelm approved these changes

2024-12-04 19:49 UTC, sihyung-maxim approved these changes

2024-12-05 07:31 UTC, ozersa approved these changes

2024-12-06 17:51 UTC, merged