feat(zephyr): Add MAX78000 to Zephyr folder
analogdevicesinc/msdk pull request #1313
Opened 2024-12-23 12:35 UTC by yasinustunerg

Add MAX78000 SoC into the zephyr build system

Signed-off-by: Yasin Ustuner <yasinustuner71@gmail.com>

### Description

- Add MAX78000 into the zephyr build system
- Add I2C related clock speed definitions

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-12-24 07:40 UTC, hfakkiz requested changes

2024-12-24 07:40 UTC, hfakkiz commented on Libraries/zephyr/MAX/Include/wrap_max32_tmr.h
> +#if !defined(CONFIG_SOC_MAX78002) && !defined(CONFIG_SOC_MAX778000)
Fix typo please.

2024-12-24 07:49 UTC, hfakkiz commented on Libraries/zephyr/MAX/Source/MAX78000/CMakeLists.txt
> +if (CONFIG_SOC_FLASH_MAX32)
Please add "CONFIG_HWINFO_MAX32" to if statement of HWINFO driver's dependencies (AES, FLC and TRNG). ([Related PR](https://github.com/analogdevicesinc/msdk/pull/1292))

2024-12-24 07:59 UTC, hfakkiz commented on Libraries/zephyr/MAX/Include/wrap_max32_sys.h
> +    defined(CONFIG_SOC_MAX78002) || defined(CONFIG_SOC_MAX78000)
Please handle clock differences here. "MXC_SYS_CLOCK_ERFO" macro is not defined for MAX78000.

2024-12-24 08:13 UTC, hfakkiz commented on Libraries/zephyr/MAX/Source/MAX78000/max78xxx_system.c
> +void max32xx_system_init(void) {}
As I see, "MXC_ICC_Enable(MXC_ICC0)" line required in here. Please check [system_max78000.c](https://github.com/analogdevicesinc/msdk/blob/main/Libraries/CMSIS/Device/Maxim/MAX78000/Source/system_max78000.c#L134) file.

2025-01-06 12:18 UTC, yasinustunerg commented on Libraries/zephyr/MAX/Source/MAX78000/CMakeLists.txt
> +if (CONFIG_SOC_FLASH_MAX32)
Done

2025-01-06 12:18 UTC, yasinustunerg commented on Libraries/zephyr/MAX/Include/wrap_max32_sys.h
> +    defined(CONFIG_SOC_MAX78002) || defined(CONFIG_SOC_MAX78000)
Done

2025-01-06 12:57 UTC, hfakkiz approved these changes

2025-01-06 22:28 UTC, sihyung-maxim commented
/clang-format-run

2025-01-08 20:30 UTC, sihyung-maxim reviewed
Just saw the MAX32680 in these files. The ME20 (MAX32680) is not supported by the company anymore. It's been neglected from the MSDK since its announcement sometime last year. It might be a good idea to remove MAX32680 references.

2025-01-08 20:32 UTC, sihyung-maxim commented
> Just saw the MAX32680 in these files. The ME20 (MAX32680) is not supported by the company anymore. It's been neglected from the MSDK since its announcement sometime last year. It might be a good idea to remove MAX32680 references.

Thoughts? @hfakkiz @ttmut @ozersa

2025-01-09 06:26 UTC, ttmut commented
> > Just saw the MAX32680 in these files. The ME20 (MAX32680) is not supported by the company anymore. It's been neglected from the MSDK since its announcement sometime last year. It might be a good idea to remove MAX32680 references.
> 
> Thoughts? @hfakkiz @ttmut @ozersa

I had not heard about that. We already upstreamed it to Zephyr so it will have to be deprecated as well if we are to proceed with removing MAX32680 support.

2025-01-10 08:33 UTC, yasinustunerg commented
Hi @sihyung-maxim, I am waiting for this PR to release zephyr. Could you review it?

2025-01-10 08:48 UTC, ozersa commented
> > Just saw the MAX32680 in these files. The ME20 (MAX32680) is not supported by the company anymore. It's been neglected from the MSDK since its announcement sometime last year. It might be a good idea to remove MAX32680 references.
> 
> Thoughts? @hfakkiz @ttmut @ozersa

Can be removed, but shall be handled by a different PR/task, please send an email on this purpose to start an action.

2025-01-10 12:08 UTC, ttmut approved these changes

2025-01-13 14:28 UTC, gkhnclkmxm approved these changes

2025-01-13 15:53 UTC, sihyung-maxim approved these changes

2025-01-13 16:08 UTC, sihyung-maxim reviewed
Forgot this is a new calendar year. Need to update the copyrights too. Will approve and merge once the copyrights are updated.

`Copyright (C) 2023-2025 Analog Devices, Inc.`

2025-01-13 16:09 UTC, sihyung-maxim commented
> > > Just saw the MAX32680 in these files. The ME20 (MAX32680) is not supported by the company anymore. It's been neglected from the MSDK since its announcement sometime last year. It might be a good idea to remove MAX32680 references.
> > 
> > 
> > Thoughts? @hfakkiz @ttmut @ozersa
> 
> Can be removed, but shall be handled by a different PR/task, please send an email on this purpose to start an action.

Sounds good. I'll talk to Lorne so we can fully deprecate from the MSDK side.

2025-01-13 17:03 UTC, yasinustunerg commented
> Forgot this is a new calendar year. Need to update the copyrights too. Will approve and merge once the copyrights are updated.
> 
> `Copyright (C) 2023-2025 Analog Devices, Inc.`

Hi @sihyung-maxim , I updated the copyrights.

2025-01-13 19:11 UTC, sihyung-maxim approved these changes

2025-01-13 19:14 UTC, sihyung-maxim commented
/clang-format-run

2025-01-13 19:41 UTC, merged