feat(PeriphDrivers): Add SPI v2 support to MAX32690
analogdevicesinc/msdk pull request #964
Opened 2024-03-26 18:35 UTC by sihyung-maxim

### Description

This PR adds SPI v2 support to MAX32690.

### Checklist Before Requesting Review

- [ ] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

2024-03-27 15:07 UTC, lorne-maxim approved these changes

2024-03-29 20:36 UTC, sihyung-maxim commented
The Build_Examples workflow is failing because it can't find the new SPI source files... Had this same issue when the AI87 SPI v2 dirivers were added. It doesn't seem like the runner references the PR's Libraries?

2024-04-01 21:23 UTC, Jake-Carter commented
> The Build_Examples workflow is failing because it can't find the new SPI source files... Had this same issue when the AI87 SPI v2 dirivers were added. It doesn't seem like the runner references the PR's Libraries?

@sihyung-maxim I can replicate the error if I build PeriphDrivers for v1 and try to build the v2 example immediately afterwards.  The build system doesn't know to re-build the library if settings have changed _across different projects_.

We worked around this with Cordio by modifying the name/filepath of the library file itself.  i.e. `max32655_baremetal_T2_softfp` vs `max32655_freertos_T1_hardfp`.

I implemented this for the PeriphDrivers in https://github.com/analogdevicesinc/msdk/pull/964/commits/71bf46a993c80dcbb64aa414412120eaf1cebf12

2024-04-01 22:21 UTC, Jake-Carter requested changes
Can you also update the developer note in the UG to list the devices that are currently supported by the V2 drivers?

2024-04-03 00:54 UTC, Jake-Carter approved these changes

2024-04-03 00:54 UTC, merged